require('dotenv').config();
const express=require('express'), session=require('express-session'), path=require('path'), multer=require('multer');
const { createClient }=require('@supabase/supabase-js');
const app=express(); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:20}});
const PORT=process.env.PORT||3000, ADMIN_USER=process.env.ADMIN_USER||'admin', ADMIN_PASS=process.env.ADMIN_PASS||'changeme123', SESSION_SECRET=process.env.SESSION_SECRET||'change-me';
if(process.env.NODE_ENV==='production' && (!process.env.ADMIN_USER||!process.env.ADMIN_PASS||!process.env.SESSION_SECRET)) { throw new Error('Production requires ADMIN_USER, ADMIN_PASS and SESSION_SECRET environment variables.'); }
const AGENT_NAME=process.env.AGENT_NAME||'Asfak Properties',AGENT_PHONE=process.env.AGENT_PHONE||'+91 62045 23773',AGENT_WHATSAPP=process.env.AGENT_WHATSAPP||'919852229966',AGENT_EMAIL=process.env.AGENT_EMAIL||'asfakahmed9852@gmail.com',AGENT_CITY=process.env.AGENT_CITY||'Bangalore';
if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY) console.warn('Supabase not configured. Add credentials to .env');
const supabase=createClient(process.env.SUPABASE_URL||'https://placeholder.supabase.co',process.env.SUPABASE_SERVICE_ROLE_KEY||'placeholder');
const BUCKET=process.env.SUPABASE_STORAGE_BUCKET||'property-images';
const fmt=n=>{n=Number(n)||0;return n>=1e7?(n/1e7).toFixed(2).replace(/\.00$/,'')+' Cr':n>=1e5?(n/1e5).toFixed(2).replace(/\.00$/,'')+' L':String(n)};
const db={
 async listings(){const {data,error}=await supabase.from('properties').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]},
 async property(id){const {data,error}=await supabase.from('properties').select('*').eq('id',id).single();if(error)throw error;return data},
 async save(p){const q=p.id?supabase.from('properties').update(p).eq('id',p.id).select().single():supabase.from('properties').insert(p).select().single();const {data,error}=await q;if(error)throw error;return data},
 async del(id){const {error}=await supabase.from('properties').delete().eq('id',id);if(error)throw error},
 async leads(){const {data,error}=await supabase.from('leads').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]},
 async lead(p){const {error}=await supabase.from('leads').insert(p);if(error)throw error},
 async updateLead(id,p){const {error}=await supabase.from('leads').update(p).eq('id',id);if(error)throw error}, async delLead(id){const {error}=await supabase.from('leads').delete().eq('id',id);if(error)throw error}
};
app.set('view engine','ejs');app.set('views',path.join(__dirname,'views'));app.set('trust proxy',1);app.use(express.static(path.join(__dirname,'public')));app.use(express.urlencoded({extended:true}));app.use(express.json());app.use(session({secret:SESSION_SECRET,resave:false,saveUninitialized:false,cookie:{maxAge:28800000,httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax'}}));
app.use((req,res,next)=>{res.locals.site={AGENT_NAME,AGENT_PHONE,AGENT_WHATSAPP,AGENT_EMAIL,AGENT_CITY};res.locals.formatPrice=fmt;res.locals.isAdmin=!!req.session.isAdmin;next()});
const admin=(req,res,next)=>req.session.isAdmin?next():res.redirect('/admin/login');const err=(res,e)=>{console.error(e);res.status(500).send('Database error. Please check Supabase configuration.')};
app.get('/',async(req,res)=>{try{const x=await db.listings();res.render('index',{featured:x.filter(p=>p.status==='available'&&p.featured!==false).slice(0,6)})}catch(e){err(res,e)}});
app.get('/listings',async(req,res)=>{try{let x=await db.listings();const{location,bhk,maxPrice}=req.query;if(location)x=x.filter(p=>(p.location||'').toLowerCase().includes(location.toLowerCase()));if(bhk)x=x.filter(p=>(p.bhk||'').toLowerCase().includes(bhk.toLowerCase()));if(maxPrice)x=x.filter(p=>Number(p.price_min||p.priceMin)<=Number(maxPrice)*1e5);res.render('listings',{listings:x,query:req.query})}catch(e){err(res,e)}});
app.get('/property/:id',async(req,res)=>{try{let p=await db.property(req.params.id);p.images=p.images||[];p.amenities=p.amenities||[];const related=(await db.listings()).filter(x=>x.id!==p.id).slice(0,2);res.render('property',{property:p,related})}catch(e){res.status(404).send('Property not found')}});
app.get('/contact',(req,res)=>res.render('contact',{submitted:false,error:null,propertyTitle:req.query.property||''}));app.post('/contact',async(req,res)=>{const{name,phone,email,message,propertyTitle}=req.body;if(!name||!phone)return res.render('contact',{submitted:false,error:'Name and phone number are required.',propertyTitle:propertyTitle||''});try{await db.lead({name,phone,email:email||'',message:message||'',property_title:propertyTitle||'',status:'new',notes:'',follow_up_date:null});res.render('contact',{submitted:true,error:null,propertyTitle:''})}catch(e){err(res,e)}});
app.get('/admin/login',(req,res)=>res.render('admin-login',{error:null}));app.post('/admin/login',(req,res)=>{if(req.body.username===ADMIN_USER&&req.body.password===ADMIN_PASS){req.session.isAdmin=true;return res.redirect('/admin')}res.render('admin-login',{error:'Invalid username or password.'})});app.post('/admin/logout',(req,res)=>req.session.destroy(()=>res.redirect('/admin/login')));
app.get('/admin',admin,async(req,res)=>{try{const[x,l]=await Promise.all([db.listings(),db.leads()]);res.render('admin-dashboard',{stats:{totalListings:x.length,availableListings:x.filter(p=>p.status==='available').length,totalLeads:l.length,newLeads:l.filter(z=>z.status==='new').length},recentLeads:l.slice(0,5)})}catch(e){err(res,e)}});
app.get('/admin/leads',admin,async(req,res)=>{try{res.render('admin-leads',{leads:await db.leads()})}catch(e){err(res,e)}});app.post('/admin/leads/:id/status',admin,async(req,res)=>{try{await db.updateLead(req.params.id,{status:req.body.status});res.redirect('/admin/leads')}catch(e){err(res,e)}});app.post('/admin/leads/:id/update',admin,async(req,res)=>{try{await db.updateLead(req.params.id,{status:req.body.status,notes:req.body.notes||'',follow_up_date:req.body.followUpDate||null});res.redirect('/admin/leads')}catch(e){err(res,e)}});app.post('/admin/leads/:id/delete',admin,async(req,res)=>{try{await db.delLead(req.params.id);res.redirect('/admin/leads')}catch(e){err(res,e)}});
app.get('/admin/listings',admin,async(req,res)=>{try{res.render('admin-listings',{listings:await db.listings(),editing:null})}catch(e){err(res,e)}});app.get('/admin/listings/new',admin,(req,res)=>res.render('admin-listing-form',{listing:null}));app.get('/admin/listings/:id/edit',admin,async(req,res)=>{try{res.render('admin-listing-form',{listing:await db.property(req.params.id)})}catch(e){res.redirect('/admin/listings')}});
async function uploadFiles(files=[]){let urls=[];for(const f of files){if(!f.buffer)continue;const name=`${Date.now()}-${Math.random().toString(36).slice(2)}-${f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error}=await supabase.storage.from(BUCKET).upload(name,f.buffer,{contentType:f.mimetype,upsert:false});if(error)throw error;urls.push(supabase.storage.from(BUCKET).getPublicUrl(name).data.publicUrl)}return urls}
app.post('/admin/listings/save',admin,upload.array('photos',20),async(req,res)=>{try{const b=req.body, old=(b.existingImages||'').split('\n').map(x=>x.trim()).filter(Boolean), manual=(b.images||'').split('\n').map(x=>x.trim()).filter(Boolean), uploaded=await uploadFiles(req.files||[]), images=[...new Set([...old,...manual,...uploaded])];const p={title:b.title,builder:b.builder,location:b.location,bhk:b.bhk,price_min:Number(b.priceMin)||0,price_max:Number(b.priceMax)||0,possession:b.possession,rera:b.rera,status:b.status||'available',description:b.description||'',property_type:b.propertyType||'',area:b.area||'',carpet_area:b.carpetArea||'',map_url:b.mapUrl||'',brochure_url:b.brochureUrl||'',featured:b.featured==='on',amenities:(b.amenities||'').split(',').map(x=>x.trim()).filter(Boolean),floor_plans:(b.floorPlans||'').split('\n').map(x=>x.trim()).filter(Boolean),images};if(b.id)p.id=b.id;await db.save(p);res.redirect('/admin/listings')}catch(e){err(res,e)}});
function storagePathFromUrl(url){ const marker='/storage/v1/object/public/'+BUCKET+'/'; const i=(url||'').indexOf(marker); return i>=0?decodeURIComponent(url.slice(i+marker.length).split('?')[0]):null }
async function cleanupStorage(urls){ const paths=(urls||[]).map(storagePathFromUrl).filter(Boolean); if(paths.length){const {error}=await supabase.storage.from(BUCKET).remove(paths);if(error)throw error;} }
app.post('/admin/listings/:id/images/remove',admin,async(req,res)=>{try{let p=await db.property(req.params.id);const removed=(p.images||[]).filter(x=>x===req.body.image);p.images=(p.images||[]).filter(x=>x!==req.body.image);await cleanupStorage(removed);await db.save(p);res.redirect('/admin/listings/'+p.id+'/edit')}catch(e){err(res,e)}});app.post('/admin/listings/:id/featured',admin,async(req,res)=>{try{await db.save({id:req.params.id,featured:req.body.featured==='true'});res.redirect('/admin/listings')}catch(e){err(res,e)}});app.post('/admin/listings/:id/delete',admin,async(req,res)=>{try{const p=await db.property(req.params.id);await cleanupStorage(p.images||[]);await db.del(req.params.id);res.redirect('/admin/listings')}catch(e){err(res,e)}});
app.listen(PORT,()=>console.log('Asfak Properties running on '+PORT));
